apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingress
  namespace: auth
  annotations:
    "traefik.ingress.kubernetes.io/router.middlewares": "kc-stripprefix@kubernetescrd"
    "cert-manager.io/cluster-issuer": "le-cert-issuer"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`auth.cngei.it`)
      services:
        - kind: Service
          name: keycloak
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kc-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /auth
