apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingress
  namespace: auth
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.cngei.it`)
      services:
        - kind: Service
          name: keycloak
          port: 8080
  tls:
    secretName: kc-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kc-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kc-cert
  namespace: auth
spec:
  secretName: kc-tls
  dnsNames:
    - "auth.cngei.it"
  issuerRef:
    name: le-cert-issuer
    kind: ClusterIssuer
