apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingress
  namespace: auth
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      # match: Host(`auth.cngei.it`)
      match: PathPrefix(`/`)
      services:
        - kind: Service
          name: keycloak
          port: 8080
