apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: auth
spec:
  instances: 3
  db:
    vendor: postgres
    host: pg-cluster-rw.db.svc.cluster.local
    port: 5432
    database: keycloak
    schema: public
    usernameSecret:
      name: pg-cluster-keycloak
      key: username
    passwordSecret:
      name: pg-cluster-keycloak
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: auth2.cngei.it
