apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: auth
spec:
  instances: 3
  image: ghcr.io/cngei/kc-theme:f74306fad510a9f9e23215baa49eb88da486fd55
  startOptimized: false
  db:
    vendor: postgres
    host: pg-cluster-rw.db.svc.cluster.local
    port: 5432
    database: keycloak
    schema: public
    usernameSecret:
      name: pg-cluster-keycloak
      key: username
    passwordSecret:
      name: pg-cluster-keycloak
      key: password
  hostname:
    hostname: https://auth.cngei.it/auth
  proxy:
    headers: xforwarded
  http:
    httpEnabled: true
  additionalOptions:
    - name: http-relative-path
      value: "auth"
