apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect
  namespace: nextcloud
spec:
  redirectRegex:
    regex: "^https://cloud\\.cngei\\.it/(s|f)/(\\w+)$"
    replacement: "https://cloud.cngei.it/index.php/${1}/${2}"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cloud.cngei.it`)
      middlewares:
        - name: nextcloud-redirect
      services:
        - kind: Service
          name: nextcloud-helm
          port: 8080
  tls:
    secretName: nextcloud-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  dnsNames:
    - "cloud.cngei.it"
  issuerRef:
    name: le-cert-issuer
    kind: ClusterIssuer
