apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.6.10
    helm:
      valuesObject:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        nextcloud:
          host: cloud2.cngei.it
        persistence:
          enabled: true
          storageClass: longhorn
          size: 10Gi
          nextcloudData:
            enabled: true
            existingClaim: nextcloud-cifs-pvc
            size: 3000Gi
        redis:
          enabled: false
          auth:
            enabled: false
          global:
            storageClass: longhorn
        internalDatabase:
          enabled: false
        externalDatabase:
          type: postgresql
          enabled: true
          host: pg-cluster-rw.db.svc.cluster.local
          port: 5432
          existingSecret:
            enabled: true
            secretName: pg-cluster-nextcloud-credentials
            usernameKey: username
            passwordKey: password

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
