apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.6.10
    helm:
      valuesObject:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        nextcloud:
          host: cloud2.cngei.it
          objectStore:
            s3:
              enabled: true
              host: fsn1.your-objectstorage.com
              bucket: cngeicloud
              existingSecret: nextcloud-s3-secret
              usePathStyle: true
              secretKeys:
                accessKey: username
                secretKey: password
        redis:
          enabled: false
          auth:
            enabled: false
          global:
            storageClass: longhorn
        internalDatabase:
          enabled: false
        externalDatabase:
          type: postgresql
          enabled: true
          host: pg-cluster-rw.db.svc.cluster.local
          port: 5432
          existingSecret:
            enabled: true
            secretName: pg-cluster-nextcloud-credentials
            usernameKey: username
            passwordKey: password
        persistence:
          enabled: true
          storageClass: longhorn

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
