apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
      component: server
  template:
    metadata:
      labels:
        app: immich
        component: server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.133.0-release
          ports:
            - containerPort: 2283
          envFrom:
            - configMapRef:
                name: immich-env
            # optionally use a secret for sensitive envs
            # - secretRef:
            #     name: immich-secrets
          volumeMounts:
            - name: upload-data
              mountPath: /usr/src/app/upload
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 2283
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 2283
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: upload-data
          hostPath:
            path: /immichbox
            type: Directory
