apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: immich
spec:
  replicas: 2
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
        - name: immich
          volumeMounts:
            - name: immich-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 4096Mi
          image: ghcr.io/immich-app/immich-server:v1.143.1
          ports:
            - containerPort: 2283
              protocol: TCP
          env:
            - name: IMMICH_PORT
              value: "2283"
            - name: UPLOAD_LOCATION
              value: "/data"
#            - name: REDIS_HOSTNAME
#              value: "redis-cluster-leader.redis.svc.cluster.local"
            - name: DB_HOSTNAME
              value: "immich-cluster-rw.db.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE_NAME
              value: "immich"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-immich-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-immich-credentials
                  key: password
          imagePullPolicy: Always
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-cifs-pvc