apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-cifs-pv
  namespace: immich
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "smb"
  mountOptions:
    - dir_mode=0770
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: immich-cifs-pv
    volumeAttributes:
      source: "//u462617.your-storagebox.de/backup"
    nodeStageSecretRef:
      name: immich-cifs-creds
      namespace: immich
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-cifs-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: immich-cifs-pv
  storageClassName: "smb"
