apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
  namespace: wordpress
spec:
  secretName: wordpress-tls
  duration: 8760h
  renewBefore: 360h
  dnsNames:
    - "cngei.it"
    - "www.cngei.it"
    - "new.cngei.it"
    - "webdav-www.cngei.it"
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
