apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
  namespace: wordpress
spec:
  rootPasswordSecretKeyRef:
    name: wordpress-mariadb-root-password
    key: password
  username: wordpress
  passwordSecretKeyRef:
    name: wordpress-mariadb-password
    key: password
  database: wordpress
  port: 3306
  storage:
    size: 10Gi
    storageClassName: longhorn
  metrics:
    enabled: false
  replicas: 1
