apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jira-ingress
  namespace: jira
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jira.cngei.it`)
      services:
        - kind: Service
          name: jira
          port: 80
  tls:
    secretName: jira-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jira-cert
  namespace: jira
spec:
  secretName: jira-tls
  dnsNames:
    - "jira.cngei.it"
  issuerRef:
    name: le-cert-issuer
    kind: ClusterIssuer
