kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-pg
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  dataLocality: "strict-local"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 3
  storage:
    size: 20Gi
    storageClass: longhorn-pg
  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: pg-cluster-keycloak
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pg-cluster-keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: pg-cluster
