apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
spec:
  instances: 2
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
  storage:
    size: 5Gi
    storageClass: longhorn-pg
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  bootstrap:
    initdb:
      database: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
    owner: immich
    secret:
      name: pg-cluster-immich-credentials
    dataChecksums: true
    encoding: "UTF8"
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: pg-cluster-immich-credentials
