apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
spec:
  instances: 2
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
  storage:
    size: 5Gi
    storageClass: longhorn-pg
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: pg-cluster-immich-credentials
