apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-nodeport
  namespace: db
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: pg-cluster
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432