
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-cn27-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-multi-wordpress
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-cn27
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-cn27
  template:
    metadata:
      labels:
        app: wordpress-cn27
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: wordpress
      containers:
        - name: wordpress
          image: wordpress:7-php8.5-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-multi-mariadb.wordpress.svc.cluster.local:3306
            - name: WORDPRESS_DB_USER
              value: user-cn27
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-cn27-mariadb-password
                  key: password
            - name: WORDPRESS_DB_NAME
              value: db-cn27
            - name: HTTPS
              value: "on"
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                $_SERVER['HTTPS'] = 'on';
                if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'http') {
                    $_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https';
                }
          volumeMounts:
            - name: wordpress-cn27-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-cn27-data
          persistentVolumeClaim:
            claimName: wordpress-cn27-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-cn27
  namespace: wordpress
spec:
  selector:
    app: wordpress-cn27
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
