apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-multi-mariadb
  namespace: wordpress
spec:
  rootPasswordSecretKeyRef:
    name: wordpress-multi-root-password
    key: password
  port: 3306
  storage:
    size: 10Gi
    storageClassName: longhorn-multi-wordpress
  metrics:
    enabled: false
  replicas: 1
#  replicasAllowEvenNumber: true
#  replication:
#    enabled: true
  primaryService:
    type: ClusterIP
  secondaryService:
    type: ClusterIP
  nodeSelector:
    node-role.kubernetes.io/worker: wordpress
