apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cnpg
  namespace: db
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
