apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: db-operators
  namespace: db
spec:
  targetNamespaces:
    - db
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cnpg
  namespace: db
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
